package Player;

//UN ELEMENTO MULTIMEDIALE:
    //TITOLO
  //INTERFACCIA RIPRODUCI:  METODO:PLAY, ALZA-VOLUME, ABBASSA-VOLUME
  //INTERFACCIA VISUALIZZA: METODO: AUMENTA-LUCE, DIMINUISCI-LUCE

//VARIABILI PER RIPRODUCIBILI:DURATA(INT),VOLUME(INT)
//DEVONO RITORNARE: RIPETE TITOLO * DURATA, + !*VOLUME
//1A STAMPA PER RIGA
//AUDIO:
//VIDEO:

//VARIABILE VISUALIZZA: LUMINOSITA'(INT)
//DEVONO RITORNARE: RIPETE TITOLO * DURATA, + !*VOLUME + * X LUMINOSITA'
//1A STAMPA PER RIGA

//IMMAGINE: METODO:SHOW
//VIDEO:

//DEVE RICEVERE 5 ELEMENTI DA TASTIERA E POI CHIEDE RIPETUTAMENTE ALL'UTENTE UN NUMERO DA 1 A 5 OPPURE 0 PER FINIRE
//SERVE UN ARRAY

public abstract class Multimediale {
    protected String titolo;

    public abstract void inizia();

    public Multimediale(String titolo) {
        this.titolo = titolo;
    }
}
